name: Keep Render Alive
on:
  schedule:
    - cron: '*/10 * * * *' # Pings every 10 minutes to stay within Render's 15min window
  workflow_dispatch: # Allows you to trigger it manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -I https://meteosran.onrender.com/ping
